// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.fuchsia:
      // TODO: Handle this case.
      case TargetPlatform.linux:
      // TODO: Handle this case.
      case TargetPlatform.windows:

      // TODO: Handle this case.
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCs2WhsjJhzIHdg7rlfcCOyRHIDY_OMxk',
    appId: '1:368911668418:android:e3f469fdc4a65a6511d75b',
    messagingSenderId: '368911668418',
    projectId: 'emi-app-2dbd3',
    storageBucket: 'emi-app-2dbd3.appspot.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    iosBundleId: 'com.sameer.emicalculation',
    //iosClientId: '480746930279-2rvmvdtb4499gt56teddeidmivbalsbt.apps.googleusercontent.com',
    apiKey: 'AIzaSyBg8eehU3fkBO4-pB6dIfE4f-cgAl-MC6o',
    appId: '1:480746930279:ios:b3d413b247ad1d13aa94c2',
    messagingSenderId: '368911668418',
    projectId: 'emi-app-2dbd3',
    storageBucket: 'emi-app-2dbd3.appspot.com',
  );
}
